Migrate importer folder to the project folder structure
aicenter/road-graph-tool pull request #57
Opened 2024-07-12 17:49 UTC by domupls

2024-08-15 09:15 UTC, marekcuchy requested changes

2024-08-15 09:15 UTC, marekcuchy commented on python/scripts/process_osm.py
> +    elif tag == "-d":
Please add a brief description of what each case is handling. While the error handles are quite clear from the messages, the rest is not so much.

2024-08-15 09:15 UTC, marekcuchy commented on python/tests/data/test.osm
The other test files are well-named. This file is used to test what?

2024-08-15 12:06 UTC, marekcuchy commented on python/scripts/process_osm.py
> +def process_osm_command(tag, input_file, output_file):
or should it be: run_osm_processing?

2024-08-21 08:48 UTC, marekcuchy requested changes

2024-08-21 08:48 UTC, marekcuchy commented on python/scripts/filter_osm.py
> +    if not args.input_file:
This check (input_file is set) should be possible to do with the library. Usually, the parsing libraries allow the marking of specific args as mandatory and throw an exception if not set (probably it already does that already).

2024-08-21 08:48 UTC, marekcuchy commented on python/scripts/filter_osm.py
> +def check_strategy(strategy: str | None):
This function never returns false. It should return nothing instead. The usage of it within the if statement misleads that there is the possibility that it returns false.

2024-08-21 08:48 UTC, marekcuchy commented on python/scripts/filter_osm.py
> +    print(help_text)
You can generate this message "automatically" with the library.

2024-08-21 08:48 UTC, marekcuchy commented on python/scripts/filter_osm.py
> +    args = parse_args(["b", "input.osm", "10,20,30,40"])
This is probably just testing setup?

2024-08-21 08:48 UTC, marekcuchy commented on python/scripts/filter_osm.py
> +    if args.tag == "id":
change this chain of elif to a simple switch.

2024-08-21 08:48 UTC, marekcuchy commented on python/scripts/process_osm.py
> +    print(help_text)
Use the library to print the help message

2024-08-21 08:48 UTC, marekcuchy commented on python/scripts/process_osm.py
> +    if args.tag in ['d', 'i', 'ie']:
use switch. Multiple cases can be done with: `case 'd' | 'i' | 'ie'`

2024-08-29 06:38 UTC, marekcuchy requested changes

2024-08-29 06:38 UTC, marekcuchy commented on python/scripts/filter_osm.py
> +    parser.add_argument("-id", dest="relation_id", nargs="?", help="relation ID (required for 'b' tag)")
The tag 'id' and the argument '-id' are slightly confusing. Consider change.

2024-08-29 06:38 UTC, marekcuchy commented on resources/lua_styles/default.lua
> +    clean_tags(object.tags)
Delete the commented code. You can use git to find it later. The same below.

2024-08-29 09:22 UTC, domupls commented
I've also implemented args parser (#65bac23) to `main.py` to replace using of sys.argv

2024-09-02 13:23 UTC, marekcuchy approved these changes

2024-09-03 07:05 UTC, marekcuchy approved these changes

2024-09-03 07:30 UTC, marekcuchy approved these changes

2024-09-03 07:30 UTC, merged