OSM file path in importer, SSH tunnel setup, README.md fix
aicenter/road-graph-tool pull request #84
Opened 2024-09-24 12:15 UTC by domupls

OSM file path is now a required input when importing to database using `import_osm_to_db()`. I also created [`ssh.py`](https://github.com/aicenter/road-graph-tool/blob/importer/python/roadgraphtool/ssh.py) to handle SSH tunnel setup for importing data to database. 
Additionally, I added a few notes to [README.md](https://github.com/aicenter/road-graph-tool/blob/main/README.md) about aforementioned changes.

2024-09-24 19:41 UTC, marekcuchy requested changes

2024-09-24 19:41 UTC, marekcuchy commented on config-EXAMPLE.ini
> +db_type = remote ; or local
Instead, you can check if ssh exists in the config. If it is, it is certain that an SSH tunnel needs to be used.

2024-09-24 19:41 UTC, marekcuchy commented on python/roadgraphtool/ssh.py
Are you sure that the already implemented tunneling cannot be used?

2024-09-24 19:41 UTC, marekcuchy commented on python/roadgraphtool/ssh.py
roadgraphtool.db.set_ssh_to_db_server_and_set_port() does not work?

2024-09-25 07:36 UTC, domupls commented on python/roadgraphtool/ssh.py
It works now, it was poor config setup on my part.

2024-09-25 07:36 UTC, domupls commented
Changes have been made

2024-09-25 09:39 UTC, marekcuchy approved these changes

2024-09-25 09:39 UTC, merged